version: '3.1'
services:
  pgadmin:
    # use server "db", login "postgres" pwd "example"
    image: dpage/pgadmin4:6.16
    ports:
      - 8086:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
  db:
    build:
      context: "."
    image: bonitasoft/bonita-postgres
    restart: always
    depends_on:
      - demoBackup
    volumes:
      - postgresBackupVolume:/opt/bonita/dump
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  postgresBackupVolume:

